core/urls.py
from django.conf.urls.static import static
from django.contrib import admin


from django.urls import path, include

from core import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("message_service.urls")),
]
if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

message_service/urls.py
from django.urls import path

from message_service.consumers import WSConsumer
from message_service.views import (
    UserLoginView,
    MailListView,
    MailCreateView,
    MailDetailView,
    UserLogoutView,
    MailUpdateView,
)

app_name = "message_service"

# http
urlpatterns = [
    path("", UserLoginView.as_view(), name="user_login_view"),
    path("logout/", UserLogoutView.as_view(), name="user_logout_view"),
    path("mail-list/", MailListView.as_view(), name="mail_list_view"),
    path("mail-create/", MailCreateView.as_view(), name="mail_create_view"),
    path("mail-detail/<int:pk>", MailDetailView.as_view(), name="mail_detail_view"),
    path("mail-update/<int:pk>", MailUpdateView.as_view(), name="mail_update_view"),
]

# websockets
ws_urlpatterns = [path("ws/message-processing/", WSConsumer.as_asgi())]

message_service/models.py
from django.core.exceptions import ValidationError
from django.db import models


def upload_to_file(instance: "FileMessage", filename: str) -> str:
    """ "Функция для загрузки файла"""
    return f"message_{instance.message.pk}/file_{filename}"


class ImapServer(models.Model):
    name = models.CharField(max_length=20, verbose_name="Наименование imap сервера")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "IMAP Сервер"
        verbose_name_plural = "IMAP Сервера"


class Mail(models.Model):
    login = models.EmailField(verbose_name="Электронная почта")
    password = models.CharField(
        max_length=20, verbose_name="Пароль для доступа по протоколу IMAP"
    )
    server = models.ForeignKey(
        ImapServer, on_delete=models.SET_NULL, null=True, verbose_name="сервер IMAP"
    )

    class Meta:
        verbose_name = "Электронная почта"
        verbose_name_plural = "Электронные почты"


class Message(models.Model):
    title = models.TextField(verbose_name="Тема сообщения")
    date_send = models.DateTimeField(verbose_name="Дата отправки")
    date_receiving = models.DateTimeField(verbose_name="Дата получения")
    text_message = models.TextField(verbose_name="текст сообщения")
    mail = models.ForeignKey(Mail, on_delete=models.CASCADE, verbose_name="Эл.почта")

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def save(self, *args, **kwargs):
        try:
            # Проверка уникальности записи
            if self.pk is None:
                if Message.objects.filter(
                    title=self.title,
                    date_send=self.date_send,
                    date_receiving=self.date_receiving,
                    text_message=self.text_message,
                    mail=self.mail,
                ).exists():
                    raise ValidationError("Запись с такими данными уже существует.")
            super().save(*args, **kwargs)
        except ValidationError as error:
            print(error.message)


class FileMessage(models.Model):
    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        related_name="files",
        verbose_name="Сообщение",
    )
    file = models.FileField(upload_to=upload_to_file, unique=True, verbose_name="Файл")

    class Meta:
        verbose_name = "Файл"
        verbose_name_plural = "Файлы"

message_service/forms.py
from django.forms import ModelForm

from message_service.models import Mail


class MailForm(ModelForm):
    class Meta:
        model = Mail
        fields = "__all__"

message_service/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView

from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, CreateView, UpdateView

from message_service.forms import MailForm
from message_service.models import Mail


class UserLoginView(LoginView):
    """Обработка логина пользователей."""

    template_name = "login.html"
    success_url = reverse_lazy("message_service:mail_list_view")


class UserLogoutView(LoginRequiredMixin, LogoutView):
    """Обработка выхода пользователей."""

    template_name = "logout.html"
    success_url_allowed_hosts = reverse_lazy("message_service:user_login_view")


class MailListView(LoginRequiredMixin, ListView):
    """Отображение списка почтовых ящиков"""

    model = Mail
    template_name = "mail-list.html"
    context_object_name = "mails"


class MailCreateView(LoginRequiredMixin, CreateView):
    """Создание нового почтового ящика."""

    model = Mail
    template_name = "mail-create.html"
    form_class = MailForm
    success_url = reverse_lazy("message_service:mail_list_view")


class MailUpdateView(LoginRequiredMixin, UpdateView):
    """Обновление существующего почтового ящика."""

    model = Mail
    form_class = MailForm
    success_url = reverse_lazy("message_service:mail_list_view")
    template_name = "mail-update.html"


class MailDetailView(LoginRequiredMixin, DetailView):
    """Отображение деталей конкретного почтового ящика."""

    model = Mail
    template_name = "mail-detail.html"
    context_object_name = "mail"

message_service/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {% block body %}

        {% endblock %}
    </div>
</body>
</html>

message_service/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}
{% block body %}
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Login</button>
        </form>
    </div>
{% endblock %}

message_service/templates/logout.html
{% extends 'base.html' %}

{% block title %}
    Logout
{% endblock %}
{% block body %}
    <div>
        <a href="{% url 'message_service:user_login_view' %}">На страницу авторизации</a>
    </div>
{% endblock %}

message_service/templates/mail-create.html
{% extends 'base.html' %}

{% block title %}
    Добавить почту
{% endblock %}
{% block body %}
    <a href="{% url 'message_service:mail_list_view' %}">Назад</a>
    <h3>Добавьте почту</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Добавить почту</button>
    </form>
{% endblock %}

message_service/templates/mail-detail.html
{% extends 'base.html' %}

{% block title %}
    Добавить почту
{% endblock %}

{% block body %}

    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
    <div class="d-flex justify-content-between">
        <div class="load-info" id="load-info"></div>
        <a href="{% url 'message_service:mail_update_view' pk=mail.pk %}">{{ mail.login }}</a>
        <a href="{% url 'message_service:mail_list_view' %}">Назад</a>
    </div>

    <div class="progress">
        <div id="progress-bar" class="progress-bar progress-bar-striped bg-info" role="progressbar" aria-valuenow="50"
             aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <div class="loader d-inline" id="loader"></div>
    /
    <div class="loader-default d-inline" id="loader-default"></div>
    <table id="messages-table">
        <thead>
        <tr>
            <th>Тема сообщения (наименование</th>
            <th>Дата отправки</th>
            <th>Дата получения</th>
            <th>Описание или текст сообщения</th>
            <th>Кол-во прикрепленных файлов</th>
        </tr>
        </thead>
        <tbody id="messages-body">
        <!-- Здесь будут появляться строки сообщений -->
        </tbody>
    </table>

    <script>
        const host = window.location.hostname;
        const port = window.location.port;
        const wsPort = port ? port : (window.location.protocol === 'https:' ? '443' : '80');
        const wsUrl = `ws://${host}:${wsPort}/ws/message-processing/`;
        let socket = new WebSocket(wsUrl)
        let tableBody = document.getElementById('messages-body');
        let load_info = document.getElementById('load-info');
        let loader = document.getElementById('loader');
        let progress_bar = document.getElementById('progress-bar')
        let loader_default = document.getElementById('loader-default')

        socket.onopen = (event) => {
            socket.send(JSON.stringify({
                'login': '{{ mail.login }}',
                'password': '{{ mail.password }}',
                'server': '{{ mail.server.name }}'
            }))
        };

        socket.onmessage = (event) => {
            let data = JSON.parse(event.data);


            let message = data.message

            if (data.status === 300) {
                load_info.innerText = 'чтение сообщений'
            }
            if (data.status === 400) {
                load_info.innerText = 'Проблема при получения данных, проверьте учетные данные'
            }
            if (data.status === 200) {
                let count_messages = data.count_messages;
                let load_messages = data.load_messages
                loader_default.innerText = count_messages
                load_info.innerText = 'получение сообщений'
                let progress_unit = 100 / count_messages

                progress_bar.style.width = `${(count_messages - load_messages) * progress_unit}%`
                loader.innerText = load_messages

                const row = document.createElement('tr');

                const cell2 = document.createElement('td');
                cell2.textContent = message.title;
                row.appendChild(cell2);

                const cell3 = document.createElement('td');
                cell3.textContent = message.date_send;
                row.appendChild(cell3);

                const cell4 = document.createElement('td');
                cell4.textContent = message.date_receiving;
                row.appendChild(cell4);

                const cell5 = document.createElement('td');
                if (message.text_message.length > 150) {
                    cell5.textContent = message.text_message.substring(0, 150) + '...'
                } else {
                    cell5.textContent = message.text_message;
                }
                row.appendChild(cell5)
                const cell6 = document.createElement('td');
                if (message.files.length > 0) {
                    cell6.innerText = message.files.length

                }


                row.appendChild(cell6);

                // Добавление строки в тело таблицы
                tableBody.appendChild(row);

            }
        };

        socket.onerror = (error) => {
            console.error('WebSocket Error: ', error)
            loader.innerText = 'Проблема при получения данных, проверьте учетные данные'

        };
    </script>
{% endblock %}

message_service/templates/mail-list.html
{% extends 'base.html' %}

{% block title %}
    Mail List
{% endblock %}
{% block body %}
    <div class="my-5 w-100 d-flex justify-content-around">
        <div class="">
            <a class="d-block" href="{% url 'message_service:mail_create_view' %}"> Добавить почту </a>
            <a class="d-block" href="{% url 'message_service:user_logout_view' %}"> Выйти </a>
            <h5>Список почт</h5>
            {% if not mails %}
                <h4>Вы не добавили ни одной почты</h4>
            {% else %}
                <ul>
                    {% for item in mails %}
                        <li><a class="d-block"
                               href="{% url 'message_service:mail_detail_view' pk=item.pk %}">{{ item.login }}</a></li>
                    {% endfor %}
                </ul>
            {% endif %}

        </div>
        <div class="">
            <h2>Created By NIKITA PROFIR</h2>
        </div>
    </div>

{% endblock %}

message_service/templates/mail-update.html
{% extends 'base.html' %}

{% block title %}
    Обновите почту
{% endblock %}
{% block body %}
    <a href="{% url 'message_service:mail_list_view' %}">Назад</a>
    <h3>Добавьте почту</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Добавить почту</button>
    </form>
{% endblock %}